import { Inter } from "next/font/google";
import "../globals.css";
import StoreProvider from "./StoreProvider";
import Header from "@/components/Header";
import { NextIntlClientProvider } from "next-intl";
import getRequestConfig from "../../i18n";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

export default async function RootLayout({
  children,
  params,
}: Readonly<RootLayoutProps>) {
  const messages = await getRequestConfig({ locale: params.locale});
  
  return (
    <html lang={params.locale}>
      <StoreProvider>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <body className={inter.className}>
            <Header />
            <main className="lg:px-[120px] sm:px-[40px] px-[16px] bg-gray-50 h-[100vh] overflow-auto">{children}</main>
          </body>
        </NextIntlClientProvider>
      </StoreProvider>
    </html>
  );
}
